# ./roles/pbs_services/tasks/remotes.yml
---
- name: Create sync remote on pbsback
  command: >
    proxmox-backup-manager remote create {{ pbs_sync.remote.id }}
     --host {{ pbs_sync.remote.host }}
     --port {{ pbs_sync.remote.port }}
     --userid {{ pbs_sync.userid }}
     --password {{ vault_sync_password }}
     --fingerprint {{ pbs_sync.remote.fingerprint }}
  register: remote_create
  changed_when: remote_create.rc == 0
  failed_when: remote_create.rc != 0 and 'already exists' not in remote_create.stderr
  when: pbs_sync.enabled | bool
  no_log: false
  become: true
