# ./inventories/pve/hosts.yml
#
# define the host PVE servers that support Proxmox Backup Server virtual machines
all:
  children:
    pve:
      hosts:
        lala100:
          # The host for the primary PBS server
          ansible_host: 10.0.0.100
        lala150:
          # the host for the secondary PBS server
          ansible_host: 10.0.0.150
