# ./inventories/pbs-services/hosts.yml
#
# Defining the names for services. should match names assigned in pbs-bootstrap
all:
  children:
    pbs_primary:
      hosts:
        pbsfront:
    pbs_secondary:
      hosts:
        pbsback:
