# ./inventories/group_vars/pbs_hosts/vars.yml
#
# Basic configuration parameters common to both PBS instances
pbs_packages:
- rsyslog
- zfsutils-linux

zfs_pool:
  autotrim: true
  ashift: 12
  compression: on

graylog:
  type: syslog
  port: 514
  bind_address: 10.0.0.104
  protocol: udp
