# ./roles/pve-vm-create/tasks/create_vm.yml
---
- name: Merge cluster defaults into vm_spec
  set_fact:
    vm_spec: >-
      {{
        (pve_vm_defaults | default({}))
        | combine(vm_spec, recursive=True)
      }}

- name: Assert required VM fields
  assert:
    that:
    - vm_spec.target_node is defined
    - vm_spec.vmid is defined
    - vm_spec.name is defined
    - vm_spec.memory is defined
    - vm_spec.cores is defined
    - vm_spec.sockets is defined

- name: Create or update Proxmox VM
  community.general.proxmox_kvm:
    api_user: "{{ pve_api_user }}"
    api_token_id: "{{ pve_api_token_id }}"
    api_token_secret: "{{ pve_api_token_secret }}"
    api_host: "{{ pve_api_host }}"

    # General 
    node: "{{ vm_spec.target_node }}"
    vmid: "{{ vm_spec.vmid }}"
    name: "{{ vm_spec.name }}"
    onboot: "{{ vm_spec.onboot | default(omit) }}"
    # OS
    ostype: "{{ vm_spec.ostype }}"
    boot: "{{ vm_spec.boot | default(omit) }}"
    # System    
    machine: "{{ vm_spec.machine | default(omit) }}"
    bios: "{{ vm_spec.bios  }}"
    agent: "{{ vm_spec.agent | bool }}"
    # CPU
    cores: "{{ vm_spec.cores }}"
    sockets: "{{ vm_spec.sockets }}"
    # Memory
    memory: "{{ vm_spec.memory }}"
    # Disks
    scsihw: "{{ vm_spec.scsihw | default(omit) }}"
    scsi: "{{ vm_scsi }}"
    #Network
    net: "{{ vm_net }}"

    state: present
