# ./roles/pve-vm-create/tasks/render_disks.yml
---
- name: Render Proxmox disk map
  ansible.builtin.set_fact:
    vm_disks: >-
      {{
        dict(
          vm_spec.disks
          | enumerate
          | map(
              attribute=1,
              transform=lambda d, idx=loop.index0:
                {
                  (d.bus ~ idx): {
                    'storage': d.storage,
                    'size': d.size,
                    'backup': d.options.backup | bool,
                    'discard': d.options.discard
                               | default(vm_defaults.disk.discard),
                    'iothread': d.options.iothread
                                 | default(vm_defaults.disk.iothread)
                                 | bool,
                    'replicate': d.options.replicate
                                  | default(vm_defaults.disk.replicate)
                                  | bool
                  }
                }
            )
          | list
          | combine
        )
      }}
