# ./roles/pve-vm-create/tasks/render_networks.yml
---
- name: Assert network inventory shape
  assert:
    that:
    - vm_spec.networks is mapping
    - vm_spec.networks | length > 0
    fail_msg: "vm_spec.networks must be a non-empty dictionary keyed by netX"

- name: Render network map for proxmox_kvm
  set_fact:
    vm_net: >-
      {{
        vm_spec.networks
        | dict2items
        | items2dict(
            key_name='key',
            value_name='value'
          )
      }}

- name: Debug rendered net map
  debug:
    var: vm_net
  when: ansible_verbosity | int >= 2
