# ./roles/pve-vm-create/tasks/render_disks.yml
---
- name: Assert disk inventory shape
  assert:
    that:
    - vm_spec.disks is mapping
    - vm_spec.disks | length > 0
    fail_msg: "vm_spec.disks must be a non-empty dictionary keyed by scsiX"

- name: Render scsi disk map for proxmox_kvm
  set_fact:
    vm_scsi: >-
      {{
        vm_spec.disks
        | dict2items
        | items2dict(
            key_name='key',
            value_name='value'
          )
      }}

- name: Debug rendered scsi map
  debug:
    var: vm_scsi
  when: ansible_verbosity | int >= 2
