# ./roles/pve-vm-create/tasks/render_networks.yml
---
- name: Initialize network map
  ansible.builtin.set_fact:
    vm_nets: {}

- name: Render Proxmox network entries
  ansible.builtin.set_fact:
    vm_nets: >-
      {{
        vm_nets | combine({
          ('net' ~ idx): {
            'bridge': item.bridge,
            'model': item.model | default('virtio'),
            'firewall': item.options.firewall
                        | default(vm_defaults.net.firewall)
                        | bool
          }
        })
      }}
  loop: "{{ vm_spec.networks }}"
  loop_control:
    index_var: idx
    label: "{{ item.bridge }}"
