# ./inventories/host_vars/pbsback.yml
#
# Configuration values unique to each PBS instance
hostname: pbsback
fqdn: pbsback.lalalandus.com

replication:
  mac: "bc:24:11:11:2e:36"
  address: 172.16.150.5/28
  gateway: 172.16.150.1
  route_subnet: 172.16.100.0/28
  # IP of the remote PVE host gateway on the replication network 
  remote_ip: 172.16.100.1 #used only for validation

zfs_pool:
  name: dfw_pool
  device: /dev/sdb
  autotrim: "on"
  ashift: 12
  compression: "on"

# Configuration of the datastore
pbs_datastore:
  name: secondary-backups
  pool: dfw_pool
  path: /mnt/datastore/dfw
  pbs_users:
  - name: sync
    role: RemoteSyncOperator

# Gotify client config for this PBS instance.
# gotify_server (url, endpoint_name, disable_mail_to_root) is in group_vars/all.yml.
gotify_config:
  app_name: Proxmox Backup Server Back - 159
  token: "{{ vault_gotify_token.pbsback }}"

pbs_sync:
  enabled: true
  userid: sync@pbs
  direction: pull
  schedule: "02:00"
  remote:
    id: pbsfront
    host: 172.16.100.5
    port: 8007 # Explicit statement of default port
    datastore: lalaland-backups
    fingerprint: "{{ vault_pbs_fingerprint.pbsfront }}"
