# ./inventories/host_vars/pbsfront.yml
#
# Configuration values unique to each PBS instance
hostname: pbsfront
fqdn: pbsfront.lalalandus.com

replication:
  mac: "bc:24:11:c8:35:6c"
  address: 172.16.100.5/28
  gateway: 172.16.100.1
  route_subnet: 172.16.150.0/28
  # IP of the remote PVE host gateway on the replication network 
  remote_ip: 172.16.150.1 #used only for validation

zfs_pool:
  name: dal_pool
  device: /dev/sdb
  autotrim: "on"
  ashift: 12
  compression: "on"

# Configuration of the datastore
pbs_datastore:
  name: lalaland-backups
  pool: dal_pool
  path: /mnt/datastore/dal
  pbs_users:
  - name: backup
    role: DatastoreBackup
  - name: sync
    role: DatastoreReader

# Gotify client config for this PBS instance.
# gotify_server (url, endpoint_name, disable_mail_to_root) is in group_vars/all.yml.
gotify_config:
  app_name: Proxmox Backup Server Front - 109
  token: "{{ vault_gotify_token.pbsfront }}"

pbs_sync:
  enabled: false
