# ./inventories/pve/group_vars/pve/vars.yml
#

# Proxmox API interface (non-secret)
pve_api_user: ansible@pam
pve_api_token_id: automation
pve_api_host: "{{ ansible_host }}"

# Proxmox Backup Server VM definitions
pve_pbs_vms:
- vmid: 109 # define the primary PBS instance on lala100
  name: pbsfront
  target_node: lala100 # Host PVE machine name for VM
  memory: 2048
  cores: 2
  sockets: 1

  disks:
    scsi0:
      # VM boot and system disk
      storage: local-lvm
      size: 30G
      options:
        backup: false
    scsi1:
      # VM data disk. Allow default thin provisioning
      storage: local-lvm
      size: 400G
      options:
        backup: false

  networks:
    net0:
      bridge: vmbr0 # management interface defined by lala100
    net1:
      bridge: vmbr1 # replication interface defined by lala100

- vmid: 159 # define the secondary PBS instance on lala150
  name: pbsback
  target_node: lala150
  memory: 2048
  cores: 2
  sockets: 1

  disks:
    scsi0:
      # VM boot and system disk
      storage: local-lvm
      size: 30G
      options:
        backup: false
    scsi1:
      # VM data disk. Allow default thin provisioning
      storage: local-lvm
      size: 400G
      options:
        backup: false

  networks:
    net0:
      bridge: vmbr0 # management interface defined by lala150
    net1:
      bridge: vmbr1 # replication interface defined by lala150
