# ./inventories/pve/group_vars/pve/vars.yml
#

# Cluster-wide defaults
vm_defaults:
  bios: seabios
  machine: q35
  scsihw: virtio-scsi-single
  agent: true
  onboot: true
  cpu: host
  sockets: 1
  cores: 2
  memory: 4096

  disks:
    scsi0: "local-lvm:30,backup=0,discard=on,iothread=1"
    scsi1: "local-lvm:400,backup=0,discard=on,iothread=1"
  networks:
    net0: "virtio,bridge=vmbr0,firewall=1"
    net1: "virtio,bridge=vmbr1,firewall=1"

# Proxmox API interface (non-secret)
pve_api:
  host: "{{ ansible_host }}"
  user: ansible@pam
  token_id: automation
  token_secret: "{{ vault_pve_api_token }}"
  validate_certs: false

# Proxmox Backup Server VM definitions
pve_pbs_vms:
- name: pbsfront
  vmid: 109 # define the primary PBS instance on lala100
  node: lala100 # Host PVE machine name for VM

- name: pbsback
  vmid: 159 # define the secondary PBS instance on lala150
  node: lala150
