# ./roles/pbs_update/tasks/main.yml
#
- name: Enable no-subscription repo
  apt_repository:
    repo: "deb http://download.proxmox.com/debian/pbs bookworm pbs-no-subscription"
    state: present

- name: Disable enterprise repo
  apt_repository:
    repo: "deb https://enterprise.proxmox.com/debian/pbs bookworm pbs-enterprise"
    state: absent

- name: Update system
  apt:
    update_cache: yes
    upgrade: dist

- name: Disable subscription nag
  replace:
    path: /usr/share/javascript/proxmox-backup/js/proxmox-backup-gui.js
    regexp: "status\\.toLowerCase\\(\\) === 'active'"
    replace: "true"
  notify: Restart proxy  # Optional: logic to clear cache/restart service
