# ./inventories/hosts.yml
all:
  hosts:
    lala100:
      ansible_host: 10.0.0.100
    lala150:
      ansible_host: 10.0.0.150
    pbsfront:
      ansible_host: 10.0.0.109
    pbsback:
      ansible_host: 10.0.0.159

  children:
    pve_hosts:
      hosts:
        lala100:
        lala150:
    pbs_hosts:
      hosts:
        pbsfront:
        pbsback:
