# ./playbooks/pbs-service-config.yml

---
- name: Configure PBS Services
  hosts: pbs_hosts
  become: true
  gather_facts: true

  roles:
    - role: pbs_services
      tags: services
    - role: pbs_notifications
      tags: notifications
      