# playbooks/pve_vm_create.yml

---
- name: Create PBS VMs on Proxmox
  hosts: pve_hosts
  connection: local
  gather_facts: false

  tasks:
    - name: Create VMs
      include_role:
        name: pve-vm-create
      loop: "{{ pve_pbs_vms | default([])  }}"
      loop_control:
        label: "{{ item.name }}"
