# playbooks/pve_vm_create.yml

---
- name: Create PBS VMs on Proxmox
  hosts: pve
  connection: local
  gather_facts: false
  

  tasks:
    - name: Create VMs
      include_role:
        name: pve-vm-create
      loop: "{{ pve_pbs_vms }}"
      when: item.node == inventory_hostname
      loop_control:
        label: "{{ item.name }} on {{ item.node }}"